// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6BVqC0Ib5STUIZ6tRZKyhFDg57jAhmiY',
    appId: '1:750868217623:android:ba6443829ea5ee82dc8152',
    messagingSenderId: '750868217623',
    projectId: 'mindful-path-3bc36',
    storageBucket: 'mindful-path-3bc36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQbcXrOfBzKiN3VVAkKC6GdmQgJ8rzkX0',
    appId: '1:750868217623:ios:beb498c8e7054d7bdc8152',
    messagingSenderId: '750868217623',
    projectId: 'mindful-path-3bc36',
    storageBucket: 'mindful-path-3bc36.appspot.com',
    androidClientId: '750868217623-30bf0oehfcr96on35a0pkrqg4qd5al2t.apps.googleusercontent.com',
    iosClientId: '750868217623-9hk4t4vbqd48otn73ved75r9bcqt52sm.apps.googleusercontent.com',
    iosBundleId: 'com.mindfulpath.app',
  );
}
